version: 2.1

jobs:
  deploy:
    working_directory: ~/ediant-frontend
    docker:
      - image: circleci/node:12.14.1
        environment:
          TZ: Asia/Tokyo
    steps:
      - checkout
      - run:
          name: Install and build
          command: |
            yarn
            yarn prod
